### ISSUE TITLE
Problem with picture attachments as a cover

### ISSUE THREAD

**Issue by wilkobyl** [RARgames/4gaBoards#245]
When using picture attachment as a  card cover, there is an issue:
for jpg format: the color gets inverted (white text goes black etc.) and colored images are black and white

![image](https://github.com/RARgames/4gaBoards/assets/40911978/994f5ab5-6a63-43eb-aa05-5011aab219f3)

for png format: there is an empty preview for pictures with 32bit depth (not happening for 24bit depth)

![image](https://github.com/RARgames/4gaBoards/assets/40911978/efd2b79e-91dd-4d8a-83a7-5badfd29a9bc)

all isssues are also visible on the attachments part of the card view

![image](https://github.com/RARgames/4gaBoards/assets/40911978/615d1e06-6b5e-473d-b49b-727c70aca981)

webp format works as intended

**Comment by RARgames** [comment]
Some cases fixed in [966165c](https://github.com/RARgames/4gaBoards/commit/966165ccc1af991eea00e583f5ea91b87cab96d4)

Please test @wilkobyl and report back if issues still persist.

**Comment by wilkobyl** [comment]
Yes, the update fixed the issue
