### ISSUE TITLE
"Edit Title" of card in the list view and "Edit Description" of card's tasks - clicking sometimes does not work 

### ISSUE THREAD

**Issue by wilkobyl** [RARgames/4gaBoards#248]
Clicking on "Edit Title" to edit the title of the card on the list view:
![image](https://github.com/RARgames/4gaBoards/assets/40911978/5bb91a37-be24-40ba-855d-96b2b132afba)
And "Edit Description" of card's tasks:
![image](https://github.com/RARgames/4gaBoards/assets/40911978/54f92117-1b41-4a31-a4ab-4145c8496bb1)
Sometimes requires to click multiple times to open the edit popup.
Known cases: 
Clicking either edits while having simultaneously opened Edit List field seems one of the causes of the issue

its probable that the error is coming from useClossableForm

**Comment by RARgames** [comment]
@wilkobyl Please test the fix

**Comment by wilkobyl** [comment]
fixed
