### ISSUE TITLE
Wrong Germany flag

### ISSUE THREAD

**Issue by wilkobyl** [RARgames/4gaBoards#250]
Germany flag in preferences - language appears to have white stripe instead of black:
![image](https://github.com/RARgames/4gaBoards/assets/40911978/765a2a85-7275-404d-8c41-5f30788ed1a8)

**Comment by RARgames** [comment]
Fixed in [cab9528](https://github.com/RARgames/4gaBoards/commit/cab9528ec61aaec8cf5598cd3be658fa3fa47551)
