### ISSUE TITLE
Cannot drag certain elements on laptop (scroll like) - Dropdown, CardModal

### ISSUE THREAD

**Issue by RARgames** [RARgames/4gaBoards#278]
Explain @wilkobyl

**Comment by wilkobyl** [comment]
When using the touchpad on the laptop, I couldn't drag the card modal (when it had enough text for the scrollbar to appear). The same card could be moved using scroll on the mouse.
Same issue was with the dropdown in the settings -- choose language.
Other scrollbars seemed to work properly.

**Comment by RARgames** [comment]
Fixed [13f3fc3](https://github.com/RARgames/4gaBoards/commit/13f3fc395bc700ed6ecfa5f9b722545e7cf0aa6a) - @wilkobyl please verify

**Comment by wilkobyl** [comment]
fixed
