### ISSUE TITLE
Card modal bugs

### ISSUE THREAD

**Issue by wilkobyl** [RARgames/4gaBoards#334]
1.   
![image](https://github.com/user-attachments/assets/41c658b2-bdc1-487f-a3b6-0a1e0f462c25)

2. In edit time, the button says stop even if it is already not running
![image](https://github.com/user-attachments/assets/6148b3c3-e792-4aa0-bedf-ade0fb19105b)
![image](https://github.com/user-attachments/assets/0f417221-61a7-40be-a4dc-f015e1f292cb)

**Comment by RARgames** [comment]
1. Cannot reproduce - recheck
![image](https://github.com/user-attachments/assets/1d7d1b48-e320-4d0a-a412-c87c39bbdf6d)

**Comment by wilkobyl** [comment]
fixed
