### ISSUE TITLE
Impossible to change Profile picture

### ISSUE THREAD

**Issue by zarevskaya** [RARgames/4gaBoards#372]
Hello,

When I'm trying to change the profile picture, I have an issue, it's impossible.

Hope this helps:
![Screenshot_20241019_135746](https://github.com/user-attachments/assets/d014e11e-eaaf-4f0a-9a5c-4e7c9720f703)

Have a nice day!

**Comment by RARgames** [comment]
Hey, 
could you add more details? 
What browser do you use? (any plugins/extensions)
Does anything happen when you try to change it?

**Comment by zarevskaya** [comment]
Oh, sorry, of course! 

_What browser do you use?_
Firefox 
(any plugins/extensions)
uBlock. Only. I also tried disabling it. It doesn't change anything. In incognito mode too.

_Does anything happen when you try to change it?_ Nothing, only this message:
![Screenshot_20241019_135746](https://github.com/user-attachments/assets/2a12c692-8bfa-47ce-a5f8-d78bc5d58c0c)

**Comment by RARgames** [comment]
Ok, I'm not sure what might be the issue. Do you self-host using docker compose?

Could you try changing avatar on our 'work in progress' demo instance at https://demo.4gaboards.com/ and let me know if it's working there for you?

User: demo
Password: demo

**Comment by zarevskaya** [comment]
_Do you self-host using docker compose?_
That's correct. 

Oh, wait, I'm just dumb! I understand now... 

I was fooled by the window at the bottom, I thought it was a hint and not something to click on.

![Screenshot_20241019_180516](https://github.com/user-attachments/assets/83c6de8a-645b-4f8c-826e-b2a8578d6374)

-_-' 

I thought that it would directly ask me to choose my profile image.

**Comment by RARgames** [comment]
Ahh I see. Good that you figured it out. Maybe the translation is not accurate (In English there is "Upload new avatar")?

When you have avatar uploaded, it shows an additional option - delete avatar.
It's very similar to the one on Github:

![image](https://github.com/user-attachments/assets/ae9f2a35-8bd2-4933-8ae0-7e38751de7a1)

I'll think about this.

**Comment by zarevskaya** [comment]
Indeed, I understood that afterwards. Sorry for the false alarm.
