### ISSUE TITLE
Partial translation?

### ISSUE THREAD

**Issue by zarevskaya** [RARgames/4gaBoards#373]
Hello,

Some parts are not translated, in my case into French. However, it seems that the translation files are complete. Do you have an opinion?

Thanks!

**Comment by zarevskaya** [comment]
I suggest this, do the automatic translation and then I'll check. What do you think?

Good deal?

**Comment by RARgames** [comment]
Sure, I'll do that later today and let you know here when it's ready

**Comment by zarevskaya** [comment]
Cool! I will also respond quickly for proofreading. Thanks!

**Comment by RARgames** [comment]
Just updated:  d5d8b08
Release should be out in ~10 minutes.

Also please leave us a star :D if you enjoy the project.

**Comment by zarevskaya** [comment]
Gorgeous! Not only am I going to give one star, but I am preparing an article on your application. That's why I wanted to make sure everything works.

Tomorrow maximum it will be online.

**Comment by RARgames** [comment]
Thanks for that and for the proofreading!

Release should be out in ~10 minutes.

**Comment by zarevskaya** [comment]
You're welcome, I'll do a confirmation reread after the update.
