### ISSUE TITLE
Backup feature / export project to e.g. spreadsheet 

### ISSUE THREAD

**Issue by maluco68** [RARgames/4gaBoards#416]
It would be very beneficial to have a backup possibility or export to e.g. a spreadsheet

**Comment by RARgames** [comment]
Hey, thanks for the idea!

1. Right now. it is possible to export board to a `.csv` by using a context menu near the board name and clicking `Export board`.
This export creates a few csvs containing board data (actions, attachments, boards, boardMemberships, cardLabels, cardMemberships, cards, cardSubscriptions, labels, lists, projects, projectMangers, taskMemberships, tasks, users) packed into one compressed file - `.tar.gz`.

Let me know if this is something you are looking for.

We have plans to expand it to export whole projects.

2. Another option to backup (whole instance - all projects and everything) is to use `boards-backup.sh` script. [Info](https://github.com/RARgames/4gaBoards?tab=readme-ov-file#backup-and-restore) on how to use it.

**Comment by maluco68** [comment]
Thanks a lot for the quick answer and hint as i'm an newby still finding out all the possibilities with your great tool. just tried the export/import with -csv, the board i exported had a card with a picture attached, after importing, the attachment is not existing anymore. in card was a jpeg attached.

**Comment by RARgames** [comment]
I just tested it and it works for me.

I'm not sure what might be causing the issue. What version are you using (Settings/About)
Could you try doing export/import on our [demo](https://demo.4gaboards.com) instance and let me know if it is working for you?

**Comment by maluco68** [comment]
im using vers. Version: 3.1.2. the demo works fine, tried another jpg with almost the same size and works also fine.. not sure what happend.

**Comment by RARgames** [comment]
Closing, as it seems to be working correctly. Please reopen if you have more issues with it.
