### ISSUE TITLE
Card count on collapsed list not visible while zoomed

### ISSUE THREAD

**Issue by wilkobyl** [RARgames/4gaBoards#443]
Starting from 150% zoom, the collapsed list do not show amount of cards, the number go to another line.
![image](https://github.com/user-attachments/assets/2a13db85-8e6f-42ca-9770-d64fb4336692)

**Comment by RARgames** [comment]
Fixed [87db590](https://github.com/RARgames/4gaBoards/commit/87db590713f2af3e36eaafd1a5dd484baf997cc3) - Verify
